version: '3'
services:
  php-apache:
    container_name: php
    build:
      context: .
      dockerfile: .docker/Dockerfile
    image: php-apache
    ports:
      - 8080:80
    volumes:
      - .:/app
    links:
      - mysql
  mysql:
    container_name: mysql
    image: mysql:5.7
    ports:
      - 13306:3306
    environment:
      MYSQL_DATABASE: bookstore
      MYSQL_PASSWORD: dbpwd
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_USER: dbuser
